vim.opt.expandtab = true                    -- Converts tabs to spaces
vim.opt.shiftwidth = 2                      -- Spaces in each indentation
vim.opt.tabstop = 2                         -- Insert a number of spaces for a tab (eg: 2 spaces for a tab)
vim.opt.smartcase = true                    -- Activate smartcase
vim.opt.number = true                       -- Display line numbers
vim.opt.relativenumber = true               -- Display relative numbers
vim.opt.cursorline = true                   -- Highlight the cursor line
vim.opt.wrap = true                         -- Display full lines
vim.opt.splitbelow = true                   -- Forces every horizontal splits to go below the current window
vim.opt.splitright = true                   -- Forces every vertical splits to go to the right side
vim.opt.ignorecase = true                   -- Ignore both upper and lower cases in search
--vim.opt.scrolloff = 8                       -- ...
